### ISSUE TITLE
todo - due 4/6

### ISSUE THREAD

**Issue by icepeng** [icepeng/oriental-next#1]
- [x] Estimate effect, reducer
- [x] Auth actions
- [x] User effect, reducer
- [x] Survey effect, reducer
